version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      REDIS_URL_SIDEKIQ: redis://water_redis:6379
    depends_on:
      - db
      - redis

  redis:
    container_name: water_redis
    image: redis:6.2.0-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    container_name: water_sidekiq
    build: .
    command: 'bundle exec sidekiq'
    volumes:
      - .:/myapp
    environment:
      REDIS_URL_SIDEKIQ: redis://water_redis:6379
    depends_on:
      - db
      - redis
volumes:
  redis: